### ISSUE TITLE
Finalize Responsive Design

### ISSUE THREAD

**Issue by MichaelKohler** [mozillacommunitych/mozilla.ch#11]

**Comment by freaktechnik** [comment]
(mainly the two section things under get involved)

**Comment by freaktechnik** [comment]
(fixed those. Not sure if there's anything left that's wrong)

**Comment by MichaelKohler** [comment]
Todo here: define order of tiles in mobile view

**Comment by freaktechnik** [comment]
We can't really do that. We can just try to reorder them, so they look the same on mobile, but generally the order is set by the desktop order.

**Comment by MichaelKohler** [comment]
I haven't looked at the code, but I think we're using flex right? So we could just change the order without changing it in the HTML. Am I missing something?

**Comment by freaktechnik** [comment]
No, we're using a js lib that creates the most efficient layout (and tries to follow the order in the markup, if possible).

**Comment by jviereck** [comment]
> We can just try to reorder them, so they look the same on mobile, but generally the order is set by the desktop order.

Mhmm, are you sure about this? If I look at the mozilla.org website, the ordering on desktop and mobile are not related. E.g. on desktop the tiles are ordered like this:

![screen shot 2015-03-30 at 20 44 52](https://cloud.githubusercontent.com/assets/191719/6903943/d5a57426-d71d-11e4-908a-077bcf0bd1c8.png)

While on smaller screens (aka mobile) the ordering is the following:

![screen shot 2015-03-30 at 20 45 12](https://cloud.githubusercontent.com/assets/191719/6903952/e80dcc12-d71d-11e4-8244-ae9303eeb58e.png)

In both representations the DOM stays always the same. The only difference is the usage of different CSS selectors due to different `@media` queries. The ordering on the screen is also not related to the DOM ordering at all - the "Meet Firefox Hello" tile is the fist `<li>` element in the DOM but as you can see in the small-screen screenshot, it appears as second element in the small-screen view.

@freaktechnik, I trust in your statement that "they look the same on mobile, but generally the order is set by the desktop order", but given the case on mozilla.org just discussed I cannot see why this is the case. Can you give me a hint why I cannot follow your argument? Thanks!

**Comment by freaktechnik** [comment]
@jviereck mozilla.org absolutely positions each tile in their css code, which we do not do for mozilla.ch, due to the wish, that tiles should be easy to insert and remove. We're using a js lib called [masonry](http://masonry.desandro.com/) to calculate the most compact grid possible for the current space.

**Comment by jviereck** [comment]
@freaktechnik, okay, now I see the point :) Is the tile configuration stored on the server? In that case I would love to try and generate the required responsive CSS using php when the site is served.

**Comment by freaktechnik** [comment]
@jviereck: There is no configuration farther than the order in HTML (tiles are normal left floated blocks with a static position until the script calculates their final position). The script then just fills up the empty spaces that layout would generate.

**Comment by jviereck** [comment]
@freaktechnik thanks for the input! If the JS script can compute the positions based on the HTML order, which the PHP script knows about, then I think it should be possible to compute the positions in PHP already and emit the correct css `@media` definitions.

At this point, I think it's fine to use the JS version and don't hold back the site launch from it. If you don't mind I would still like to take a look at creating the CSS with the `@media` queries and thereby removing the necessity for the JS library at some point later (which might be in 3 weeks or so...).

**Comment by freaktechnik** [comment]
Sure. The sizes of tiles are defined by the promo- classes and they generally have 20px of spacing.

**Comment by MichaelKohler** [comment]
assigning Julian, if he wants to look into it :)
