### ISSUE TITLE
MozillaCH Firefox OS Apps

### ISSUE THREAD

**Issue by MichaelKohler** [mozillacommunitych/mozilla.ch#23]
In issue #9 we have a Tile "Firefox OS Apps from MozillaCH in Marketplace". What are candidates for that?
My ideas:
- https://marketplace.firefox.com/app/grrds-4-in-a-row-1
- https://marketplace.firefox.com/app/grrds-puzzle-1

Further SJW mentioned, that neither "ÖV Schweiz" nor "SRF Podcast" are compatible with Firefox OS 3.0. These might be good candidates too, but we should make sure that they work on all versions.

**Comment by J0WI** [comment]
What about official Mozilla Apps? Probably we need to translate them first.
Personally I like this one https://marketplace.firefox.com/app/notes

or this: https://marketplace.firefox.com/app/podcasts

**Comment by MichaelKohler** [comment]
I think as a first step we should see if we have any local content to promote.

**Comment by MichaelKohler** [comment]
I'm gonna ask TheOne if it's possible to have a page on the marketplace where we could link to.

**Comment by MichaelKohler** [comment]
This is currently not possible. So we probably can do an overlay with links to the marketplace though.

**Comment by freaktechnik** [comment]
I think we shouldn't respect FxOS 3.0 compatibility as of yet. When trying to get my minesweeper to work in the 3.0 emulator I looked on mdn, wmo, ddg and google for possible documentations of breaking changes in Firefix OS 3.0. most documentation currently only reaches to 2.3 and doesn't include any notes about breaking changes.

In my case it turned out to be a CSP issue, where the unsafe-inline statement was not properly recognized by FxOS. When debugging sinfle page apps it's extremely unlikely to see ay CSP warnings in the console, as the devtools are most likely attached after the page has loaded. Luckily I have a mulri-page app, so I eventually noticedthe errors. Either FxOS has a bug in its CSP parsing, or the default CSP has been increased.

In either case, there is no developer-accessible documentation on FxOS 3 yet, so we cannot expect compatibility yet.

**Comment by MichaelKohler** [comment]
Everything mentioned here is implemented.
