### ISSUE TITLE
Twitter feed - to big on mobile

### ISSUE THREAD

**Issue by MichaelKohler** [mozillacommunitych/mozilla.ch#39]
There are screen sizes where you get caught in the Twitter iframe and you just keep scrolling within the iframe. Maybe we can reduce the height for small devices?

**Comment by colinfrei** [comment]
I'd love to have that not be an iframe. we have code to fetch the data, we just need to display it nicely (and make sure the code works :))

That would give us more flexibility in how we display, and also have one less external request.
Personally I have a block of white there because I block twitter.

**Comment by MichaelKohler** [comment]
this is a DUPE of #33 anyway, closing this one :)
