### ISSUE TITLE
Date Locale resetting to English when changing the URL

### ISSUE THREAD

**Issue by elioqoshi** [mozillacommunitych/mozilla.ch#46]
So basically when I change the URL of mozillaCH to let's say "http://mozilla.ch/test"
It brings me to the same homepage as "http://mozilla.ch/de" yet the date locale stays english

![mozillach](https://cloud.githubusercontent.com/assets/5436686/9904504/8d5e1d44-5c7e-11e5-8875-609ddf0ad41d.jpg)

**Comment by elioqoshi** [comment]
While we are at this, it's also "Näshtes Event", not "Nächster Event"

**Comment by freaktechnik** [comment]
@elioqoshi http://www.duden.de/rechtschreibung/Event <- der oder das.

**Comment by elioqoshi** [comment]
Beat me to it! I never encountered someone in Germany saying Der Event though. Might be different in Switzerland.

**Comment by freaktechnik** [comment]
@colinfrei can we do anything about this, or is this just a symphony routing issue combined with the twig formatting?

**Comment by colinfrei** [comment]
maybe the default language is en in the app/config/parameters.yml file?

**Comment by freaktechnik** [comment]
we have a key `locale` set to `de` in there, which is why it picks the german strings. But it doesn't redirect to /de.
Edit: maybe the php intl plugin has its own fallback language setting?
Edit2: yep, apprently http://php.net/manual/en/intl.configuration.php#ini.intl.default-locale. It's probably falling back to that setting.
Edit3: @colinfrei does app.request.locale not default to de and will always hold the value from the URL? Is there a better variable to use? (see https://github.com/mozillach/mozilla.ch/blob/master/app/Resources/views/tiles/upcoming_event.html.twig#L7)
Edit4: We can use `app.request.getLocale()`, which would fall back to the default locale if none is specified (though I'd guess that already happens when the route goes to the root). But `test` is still seen as a locale. Can we somehow filter the possible values for locales? I guess setting a requirements in the route would solve it, and /test would return a 404.
